[tool.poetry]
name = "lastfm-github"
version = "0.1.0"
description = ""
authors = ["Daniel Carvalho <dco3@cin.ufpe.br>"]

[tool.pdm.dev-dependencies]
dev = ["pytest<6.0,>=5.2", "black<23.0.0,>=22.3.0"]

[tool.pdm.build]
includes = []
[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[project]
authors = [{ name = "Daniel Carvalho", email = "dco3@cin.ufpe.br" }]
dependencies = [
    "Flask<3.0.0,>=2.1.2",
    "imgkit<2.0.0,>=1.2.2",
    "requests<3.0.0,>=2.27.1",
    "haishoku<2.0.0,>=1.1.8",
    "python-decouple<4.0,>=3.6",
]
name = "lastfm-github"
version = "0.1.0"
description = ""

[dependency-groups]
dev = ["pytest<6.0,>=5.2", "black<23.0.0,>=22.3.0"]
